packages:
  - apps/main/content-hub-adapter-vimeo
catalog:
  '@coremedia/set-version': ^1.2.0
  '@coremedia/studio-client.base-models': 2512.0.0
  '@coremedia/studio-client.cap-base-models': 2512.0.0
  '@coremedia/studio-client.common-icons': ^2.0.1
  '@coremedia/studio-client.core-icons': 2512.0.0
  '@coremedia/studio-client.ext.eslint-config': 2512.0.0
  '@coremedia/studio-client.main.content-hub-editor-components': 2512.0.0
  '@coremedia/studio-client.main.editor-components': 2512.0.0
  '@jangaroo/build': ^3.4.1
  '@jangaroo/core': ^3.4.1
  '@jangaroo/run': ^3.4.1
  '@jangaroo/runtime': ^3.4.1
  eslint: ^9.39.2
  rimraf: ^6.1.2
catalogMode: prefer
